sensor:
  - platform: command_line
    name: Antenna Heading
    command: "ssh username@localhost cat /<install path>/rotctlpy/currentHeading.txt"

rest_command:
  rot_a:
    url: "http://localhost:5001/A"
    method: get
  rot_b:
    url: "http://localhost:5001/B"
    method: get
  rot_c:
    url: "http://localhost:5001/C"
    method: get
  rot_d:
    url: "http://localhost:5001/D"
    method: get
  rot_e:
    url: "http://localhost:5001/E"
    method: get
  rot_f:
    url: "http://localhost:5001/F"
    method: get
  rot_g:
    url: "http://localhost:5001/G"
    method: get
  rot_h:
    url: "http://localhost:5001/H"
    method: get
  rot_i:
    url: "http://localhost:5001/I"
    method: get
  rot_j:
    url: "http://localhost:5001/J"
    method: get
  rot_u:
    url: "http://localhost:5001/U"
    method: get
  rot_l:
    url: "http://localhost:5001/L"
    method: get
